CREATE TABLE IF NOT EXISTS cmapss_fd001_train (
  engine_id INT NOT NULL,
  cycle INT NOT NULL,
  setting_1 DOUBLE PRECISION,
  setting_2 DOUBLE PRECISION,
  setting_3 DOUBLE PRECISION,
  s1 DOUBLE PRECISION, s2 DOUBLE PRECISION, s3 DOUBLE PRECISION, s4 DOUBLE PRECISION, s5 DOUBLE PRECISION,
  s6 DOUBLE PRECISION, s7 DOUBLE PRECISION, s8 DOUBLE PRECISION, s9 DOUBLE PRECISION, s10 DOUBLE PRECISION,
  s11 DOUBLE PRECISION, s12 DOUBLE PRECISION, s13 DOUBLE PRECISION, s14 DOUBLE PRECISION, s15 DOUBLE PRECISION,
  s16 DOUBLE PRECISION, s17 DOUBLE PRECISION, s18 DOUBLE PRECISION, s19 DOUBLE PRECISION, s20 DOUBLE PRECISION,
  s21 DOUBLE PRECISION,
  PRIMARY KEY (engine_id, cycle)
);
